### ISSUE TITLE
Dependency akrabat/rka-ip-address-middleware is abandoned 

### ISSUE THREAD

**Issue by benjaminluck** [DavidePastore/Slim-Restrict-Route#12]
The author of this package seems to have moved to the follow repository: 'https://github.com/akrabat/ip-address-middleware'. 

UPDATE: have created the following PR to solve this: https://github.com/DavidePastore/Slim-Restrict-Route/pull/13

**Comment by DavidePastore** [comment]
Fixed with #13.
