### ISSUE TITLE
Can you use a single IP in the options

### ISSUE THREAD

**Issue by DavidePastore** [DavidePastore/Slim-Restrict-Route#4]
Can I restrict route only to a given IP address?

```php
$options = array(
  'ip' => '192.168.0.1'
);

$app->get('/api/myEndPoint',function ($req, $res, $args) {
  //Your amazing route code
})->add(new \DavidePastore\Slim\RestrictRoute\RestrictRoute($options));
```

See also: https://github.com/Respect/Validation/issues/775

**Comment by rechl** [comment]
Yes you can ;) 

```php
 $options = array(
  'ip' => '192.168.0.1-192.168.0.1'
);

```
  
This seems a bit hacky, but it works

**Comment by DavidePastore** [comment]
@sgotre Thanks for your suggestion! I added a line in the documentation for this. 👍

**Comment by adarshmadrecha** [comment]
@DavidePastore The documentation at http://respect.github.io/Validation/docs/ip.html does not contain this feature / example

**Comment by DavidePastore** [comment]
@adarshmadrecha You're correct. The documentation at Respect/Validation doesn't contain this example, but you can find it in the [Slim-Restrict-Route one](https://github.com/DavidePastore/Slim-Restrict-Route#ip-address).
