### ISSUE TITLE
version lock prevents using with 0.5 version of rka-ip-address-middleware

### ISSUE THREAD

**Issue by urkle** [DavidePastore/Slim-Restrict-Route#6]
adding in this package when I have the latest ip-addres middleware (0.5.0) causes this error.

    - davidepastore/slim-restrict-route v0.1.1 requires akrabat/rka-ip-address-middleware ^0.4.0 -> satisfiable by akrabat/rka-ip-address-middleware[0.4] but these conflict with your requirements or minimum-stability.

API contract-wise there is no different between 0.4.0 and 0.5.0 so this restriction needs to be relaxed or updated.

**Comment by DavidePastore** [comment]
Thanks for your reporting! It should be fixed in 0.3.0 👍
